### ISSUE TITLE
Init fail on prem envrionment

### ISSUE THREAD

**Issue by findstar** [DevopsArtFactory/escli#6]
I don't use cloud services like AWS in my company.
In the process of initializing escli, I was asked about an AWS region.

Can you add the ability to select the type of cloud service provider?
At this time, it would be nice if the on prem environment could also be selected.
Thank you.

**Comment by sepiro2000** [comment]
It is resolved v 0.0.2. Thank you.

**Comment by sepiro2000** [comment]
`awsregion` parameter can be blank value from escli v0.0.2. If you use an elasticsearch cluster on-prem environments, you left `awsregion` parameter to blank value. Thank you. 

Provide other cloud service prodiver will be supported later version.
